name: mypy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip install -r requirements-dev.txt
    - run: mypy little_mallet_wrapper